name: parentflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code Checks-out
        uses: actions/checkout@v3
      - name: shelltask
        run: pwd;ls
      - name: "This is build job"
        uses: ./.github/workflows/flow1.yml

