name: build
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run unit test
        run: mvn test
      - name: run build
        run: mvn clean package

          